exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "dashboard.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]

      - id: ruff
        name: "Run ruff linter"

      - id: ruff-format
        name: "Run ruff formatter"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                dashboard/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                dashboard/templates/includes/.*|
                dashboard/public/js/lib/.*
            )$


  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ['--quiet']
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                dashboard/public/dist/.*|
                cypress/.*|
                .*node_modules.*|
                .*boilerplate.*|
                dashboard/templates/includes/.*|
                dashboard/public/js/lib/.*
            )$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: ['-L', '']

  - repo: https://github.com/agritheory/test_utils/
    rev: v0.17.0
    hooks:
      - id: update_pre_commit_config
      - id: validate_customizations
        always_run: true
      - id: validate_copyright
        files: '\.(js|ts|py|md)$'
        args: ['--app', 'dashboard']
      - id: clean_customized_doctypes
        args: ['--app', 'dashboard']

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
